sudo: required
services:
  - docker
before_install:
  - docker build -t robmccarthy/docker-react -f Dockerfile.dev .
script:
  - docker run robmccarthy/docker-react npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ca-central-1-863550205300"
  bucket_path: "docker-react"
  on:
    branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key:
  secure: "$AWS_SECRET_KEY"
